services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - ./shared:/app/shared
    environment:
      - MONGODB_URI=mongodb://mongo:27017/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - db_data:/data/db

volumes:
  db_data: