version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: docker/development/client.Dockerfile
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - node_modules_client:/app/client/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev
    ports:
      - "3000:3000"

  server:
    build:
      context: .
      dockerfile: docker/development/server.Dockerfile
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
      - node_modules_server:/app/server/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/app
    command: yarn dev
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/development/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VDOMAIN=${VDOMAIN:-nuxt-nest.local}
    depends_on:
      - client
      - server

  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - db_data:/data/db

volumes:
  node_modules_client:
  node_modules_server:
  db_data: